name: Build

on:
  push:
  schedule:
    - cron: '0 4 * * TUE'

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
        name: Setup QEmu
      - uses: docker/setup-buildx-action@v1
        name: Setup Docker Buildx
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        name: Build & Push
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_TAG }}